{{- $tr := .Values.traffic.tagRoute -}}
{{- $dc := .Values.traffic.dynamicConfig -}}
{{- $cr := .Values.traffic.conditionRoute -}}
apiVersion: dubbo.apache.org/v1alpha1
kind: ConditionRoute
metadata:
  name: {{ template "cp.name" . }}-conditionroute
  namespace: {{ template "system.namespaces" . }}
spec:
  enabled: {{ $cr.enabled }}
  force: {{ $cr.force }}
  scope: {{ $cr.scope }}
  runtime: {{ $cr.runtime }}
  priority: {{ $cr.priority }}
  key: {{ $cr.key }}
  configVersion: {{ $cr.configVersion }}
  conditions:
  - {{ $cr.conditions }}
---
apiVersion: dubbo.apache.org/v1alpha1
kind: DynamicConfig
metadata:
  name: {{ template "cp.name" . }}-dynamicconfig
  namespace: {{ template "system.namespaces" . }}
spec:
  configVersion: {{ $dc.configVersion }}
  scope: {{ $dc.scope }}
  key: {{ $dc.key }}
  configs:
  - side: {{ $dc.side }}
    match:
      application:
        oneof:
        - exact: {{ $dc.exact }}
---
apiVersion: dubbo.apache.org/v1alpha1
kind: TagRoute
metadata:
  name: {{ template "cp.name" . }}-tagroute
  namespace: {{ template "system.namespaces" . }}
spec:
  configVersion: {{ $tr.configVersion }}
  force: {{ $tr.force }}
  enabled: {{ $tr.enabled }}
  priority: {{ $tr.priority }}
  key: {{ $tr.key }}
  tags:
  - name: {{ $tr.name }}
